### ISSUE TITLE
Access to Aruba Central fails with 400 Bad Request Request Header Or Cookie Too Large nginx

### ISSUE THREAD

**Issue by GorazdKikelj** [aruba/central-automation-studio#4]
Click on AP / Switch / GW link that is redirected to Aruba Central does not open the requested page but return 400 error.

400 Bad Request
Request Header Or Cookie Too Large
nginx

Using docker with local proxy.

Best, Gorazd

**Comment by GorazdKikelj** [comment]
Redacted link is 

https://sso.common.cloud.hpe.com/as/authorization.oauth2?client_id=aquila-user-auth&redirect_uri=https%3A%2F%2Fcommon.cloud.hpe.com%2Fauthentication%2F...

redacted user data.

**Comment by wifidownunder** [comment]
For the links to work correctly you will need to be already logged into Aruba Central - once you login, the links should owkr correctly.
