### ISSUE TITLE
SSID Deployment had issues pushing selected SSIDs with spaces

### ISSUE THREAD

**Issue by engineer-josue** [aruba/central-automation-studio#5]
I created a new SSID that I wanted to push to just select APs, but since I have SSIDs with spaces in them, the script was pushing the SSIDs "SSID space", "SSID-nospace", "SSID space" which would cause the AP to just default to #ALL# or the first SSID in list. 

I cloned the repo and had chatgpt revised the issue under wlan.js line 1076 // Get Selected SSIDs

Using the following corrected my use case and tested selecting various combinations of SSIDs to a test AP. 

	// Get Selected SSIDs REVISED
 	var select = document.getElementById('wlanselector');
	var selectedSSIDs = [...select.selectedOptions].map(option => option.value.replace(/"/g, ''));
	selectedSSIDstring = selectedSSIDs.join(',');

ChatGPT- This will remove any quotes from the individual SSID strings before joining them. The selectedSSIDstring will then be in the format "SSID space, SSID-Guest" or whatever SSIDs are selected. If 'selectAllSSIDs' is checked, selectedSSIDstring will be set to '*'.

**Comment by wifidownunder** [comment]
Thanks for the improvement! I've incorporated the change and it will go in the next update.
