### ISSUE TITLE
Where can I find the latest version of the Docker image?

### ISSUE THREAD

**Issue by Kaan-Deltics** [aruba/central-automation-studio#7]
Hi,
Thanks for this awesome project!
Where can I find the latest version of the Docker image?
https://central.wifidownunder.com is currently on version v1.35.1 and the image on Docker Hub is on version 1.31.0 (6 months old) and so is this repo.

https://central.wifidownunder.com/source is also not up to date and linking to version 1.28

Thanks!

**Comment by wifidownunder** [comment]
I have updated the files here, in DockerHub and at https://central.wifidownunder.com/source
