### ISSUE TITLE
No amd64 image on Docker Hub

### ISSUE THREAD

**Issue by Linkk93** [aruba/central-automation-studio#9]
Hi all,

I tried installing the new docker image on an Ubuntu server vm, but I get the following error:

`WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v2) and no specific platform was requested`

Which is correct because there is only an ARM version on Docker Hub:
https://hub.docker.com/r/arubahpe/central-automation-studio/tags

I have built the container from the github source and it works great, but maybe you can add an amd64 version to docker hub for the future?

**Comment by wifidownunder** [comment]
Latest Docker build is now built for both arm64 and amd64
<img width="684" alt="image" src="https://github.com/aruba/central-automation-studio/assets/101156452/271df490-537c-452f-8160-c6f6bb190533">
